### ISSUE TITLE
Remote Admin path for forestry.io

### ISSUE THREAD

**Issue by toptens** [statichunt/geeky-hugo#10]
Hi,
I am trying to access my forestry admin panel from **mydomain.com/admin** url. I followed the forestry [guidelines](https://forestry.io/docs/editing/remote-admin/#deploying-the-remote-admin) to use this remote admin feature. But failed to get my desired function. Where do I will store the Forestry admin file for admin path?

Can you specify me which is the correct destination for this hugo theme?

**Comment by tfsomrat** [comment]
Hello @toptens 

Thanks for choosing our theme, here is a video documentation about how to setup forestry, hope it will help you out https://youtu.be/ResipmZmpDU
