### ISSUE TITLE
Minify of already minified javascript jumbles variables

### ISSUE THREAD

**Issue by gaetawoo** [statichunt/geeky-hugo#13]
https://github.com/statichunt/geeky-hugo/blob/7343e01609e136c98c3eeb5614e1c3c3c9afdb55/layouts/partials/script.html#L11

When already minified javascript is concatenated with a lot of other javascript, then all gets minified together, the variables get jumbled and functions no longer work. Specifically, the switching between Featured and Recent posts in the side widget. Clicking the Recent button causes an error because it's trying to run a method on an object that doesn't exist for that object because the object's variable name has changed from what it was supposed to be.

@vietanhdev solved this in his version of the theme by not concatenating all the scripts, minifying, then adding it to the html.... but instead referencing the script files directly and unmodified. This not only avoids the issue here but also makes for a significantly cleaner html page.

**Comment by tfsomrat** [comment]
@gaetawoo 

thanks for your information, this issue has been fixed now. have a good day
