### ISSUE TITLE
What was the reasoning for using .Scratch variables instead of custom $var := for initialize and $var = for assignment

### ISSUE THREAD

**Issue by gaetawoo** [statichunt/geeky-hugo#14]
These features have been in Hugo since v0.48 so I'm curious as to why .Scratch is being used? 

https://gohugo.io/templates/introduction/#variables

**Comment by tfsomrat** [comment]
Hello @gaetawoo 

This is how we code, is there any issue you are facing? we would love to solve it if there is any issue. thank you

**Comment by gaetawoo** [comment]
With Hugo v0.47.0 and earlier you had to use a Scratch because you could not assign a new value to a variable after it had been initialized.

The underlying Go limitation was removed over 3 years ago with https://github.com/golang/go/issues/10608.

Using $var :=   and then $var = results in modern syntax for Hugo templates, and cleaner, more readable templates. Might want to consider it. Thank you for the response.
