### ISSUE TITLE
How/where to style figcaption

### ISSUE THREAD

**Issue by gaetawoo** [statichunt/geeky-hugo#15]
Hello, I'm having some trouble. I'd like to style 	`<figcaption>` since as of now it looks just like the regular text. I feel it should be distinctly different... like bold, maybe smaller and centered.

How and where do I go about styling this?

**Comment by sajedur007** [comment]
Hello @gaetawoo 

thanks for choosing this theme, you can add or change any style from `exampleSite/assets/scss/custom.scss` file

**Comment by tfsomrat** [comment]
Hello @gaetawoo 

thanks for choosing this theme, you can add or change any style from `exampleSite/assets/scss/custom.scss` file
