### ISSUE TITLE
Why is frontmatter parameter `type` used in a way to break Hugo's `type` keyword?

### ISSUE THREAD

**Issue by anakinsleftleg** [statichunt/geeky-hugo#16]
This theme uses the `type` parameter in front matter to determine what posts will be featured or not. But Hugo already has the `type` frontmatter keyword reserved for determining or specifying the type of a content in order to specify what templates to use during build.

Why would this theme be designed to use `type` in a way that conflicts with Hugo? This causes the user to experience non-standard and unexpected behavior.

**Comment by mehedi-sharif** [comment]
Hello @anakinsleftleg 
thanks for your concern. we will fix it when we can. or if you want, you can create a PR to fix this issue and make some contribution to this theme. thanks
