### ISSUE TITLE
Multilingual Mode: help wanted?

### ISSUE THREAD

**Issue by maovidal** [statichunt/geeky-hugo#27]
Hi:

I'm considering to implement multilingual mode for this template and I have been already checking the code of https://github.com/statichunt/iwriter-hugo

I've noticed per #24 that you are working on a big update for this theme. Will that update contain support for multilingual mode? 

Otherwise, Is this something that can be considered to be merged on this repo? It seems it will affect most of the current files on the repo.

Thank you!

**Comment by tfsomrat** [comment]
Hello @maovidal 

Thanks for your interest in this theme. we don't want to add multilingual in this theme right now, it will conflict with our works. let us publish the update first. thank you for being with us. have a nice day.

**Comment by tfsomrat** [comment]
Hello again, We just launched our v2 version. and everything will be straightforward now. we will think about multilingual support for this theme in the future. thank you.
