### ISSUE TITLE
404 for list view of a tag

### ISSUE THREAD

**Issue by ralexrdz** [statichunt/geeky-hugo#33]
I added a this line on the front matter of some posts
```
tags: ["a", "b", "c"]
```

I then was able to look the terms, page same as in `/categories`, this tags on `/tags ` but when clicking one of the tags I was expecting to see a list view with the posts with certain tag, but instead I found the 404 page.

I've been looking around trying to find why categories work, but not tags, but I can't find why

![image](https://user-images.githubusercontent.com/3052915/232233220-20db3732-d247-4005-b965-22e8f6d36251.png)

![image](https://user-images.githubusercontent.com/3052915/232233266-bbed1b04-5d77-4608-a75d-b39fc283396a.png)

**Comment by tfsojon** [comment]
Hey @ralexrdz, You just need to restart the `hugo server` and that's all it takes.

**Comment by ralexrdz** [comment]
I asked hugo dev team for the expected feature https://github.com/gohugoio/hugo/issues/10901
