### ISSUE TITLE
Increase page speed up to 98

### ISSUE THREAD

**Issue by vietanhdev** [statichunt/geeky-hugo#9]
Hello,
Thank you for your beautiful theme. I've set it up for my site at <https://aicurious.io/>. I have some suggestions for you to increase your speed score to 98 (from my original score 83), like in my setup [here](https://pagespeed.web.dev/report?url=https%3A%2F%2Faicurious.io%2F&tab=desktop).

- Disable lazy loading for the banner image.
- Specify logo width/height.
- Consider increasing cache time.
- I hosted my site at Netlify - a free account.

![image](https://user-images.githubusercontent.com/18329471/148379083-522a9070-9463-44c8-b96d-49cc30d16a8d.png)

**Comment by somratpro** [comment]
Hello @vietanhdev 

Thanks for your concern, Your site looks beautiful. It will be great if you make a PR. It will help all the users of the theme.

**Comment by gaetawoo** [comment]
@vietanhdev do you have your theme source? Or could you do a pull request with your updates? Your site looks great.

The pagespeed test on mobile was in the 70s.. but desktop was 98... seems strange.

**Comment by vietanhdev** [comment]
@gaetawoo  Hello, I open-sourced my modifications [here](https://github.com/vietanhdev/geeky-curious). I modified this theme a lot, and now I don't have time to figure out what was changed and to open a pull request. Hope that my repo helps someone.
